"""Owner review screen. All untrusted proposal/evidence text uses textContent."""
PAGE = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer"><title>Owner review - Silhouette</title>
<style>
*{box-sizing:border-box}button{max-width:100%;overflow-wrap:anywhere}body{font:16px system-ui,sans-serif;background:#f4f6f8;color:#182432;margin:0}main{max-width:900px;margin:auto;padding:24px}h1{margin:0 0 8px}section{background:white;border:1px solid #cad2db;border-radius:8px;padding:20px;margin:18px 0}label{display:block;margin:12px 0 6px}input,select,textarea,button{font:inherit;padding:10px;box-sizing:border-box}input,textarea{width:100%;border:1px solid #758395;border-radius:4px}button{cursor:pointer;border:1px solid #445971;border-radius:4px;background:#eef3fa;margin:6px 6px 6px 0}button:disabled{opacity:.45;cursor:default}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f6f8;padding:12px;border-radius:4px}#status{min-height:24px;color:#354d6a}small{overflow-wrap:anywhere;display:block;color:#536273}#decision{border-left:4px solid #445971}[hidden]{display:none!important}
</style><main><h1>Owner review</h1><p>Read exact evidence before deciding. Approval never executes a procedure.</p>
<section id="login"><h2>Authenticate</h2><label for="token">Deployment owner token</label><input id="token" type="password" autocomplete="off" spellcheck="false"><button id="connect">Connect</button><small>Token stays only in this tab's memory, never saved in browser storage. Use HTTPS or a loopback connection. This is single-owner token authentication, not proof of human identity.</small></section>
<section id="workspace" hidden><button id="disconnect">Disconnect</button><label for="kind">Proposal type</label><select id="kind"><option value="claim">Claims</option><option value="procedure">Procedures</option></select><button id="refresh">Refresh queue</button><div id="queue"></div><label for="target">Inspect an existing proposal ID (including approved procedures)</label><input id="target" maxlength="200"><button id="inspect">Inspect exact item</button></section>
<p id="status" role="status" aria-live="polite">Not connected.</p>
<section id="details" hidden><h2>Exact proposal</h2><pre id="proposal"></pre><h2>Current cited evidence</h2><div id="evidence"></div><small id="digest"></small>
<div id="decision"><label for="action">Decision</label><select id="action"><option value="approve">Approve</option><option value="revoke">Revoke procedure</option></select><label for="reason">Reason (required)</label><textarea id="reason" maxlength="2000" rows="3"></textarea><label><input id="checked" type="checkbox" style="width:auto"> I reviewed this exact proposal and its evidence.</label><button id="stage">Review final decision</button><div id="confirmation" hidden><pre id="final"></pre><button id="submit">Confirm decision</button><button id="cancel">Cancel</button></div></div></section></main>
<script>
'use strict';
let token='', snapshot=null, staged=null, generation=0;
const $=id=>document.getElementById(id);
const status=text=>{$('status').textContent=text;};
function reset(){snapshot=null;staged=null;$('details').hidden=true;$('confirmation').hidden=true;$('checked').checked=false;$('reason').value='';}
function disconnect(){generation++;token='';$('token').value='';$('workspace').hidden=true;$('login').hidden=false;$('queue').replaceChildren();reset();status('Disconnected.');}
async function api(path,body){const response=await fetch('/api/owner-review/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',redirect:'error'});if(!response.ok){if(response.status===401)disconnect();throw new Error(response.status===409?'Snapshot changed or decision invalid. Refresh and review again.':'Request refused ('+response.status+').');}return response.json();}
async function queue(){const current=++generation;reset();$('queue').replaceChildren();try{const result=await api($('kind').value+'?limit=20');if(current!==generation)return;for(const item of result.proposals){const b=document.createElement('button');b.textContent=item.proposal.id+' ('+item.proposal.status+')';b.onclick=()=>open(item.kind,item.proposal.id);$('queue').append(b);}status(result.proposals.length?'Choose a proposal.':'No pending proposals.');}catch(e){status(e.message);}}
async function open(kind,id){const current=++generation;reset();try{const data=await api(encodeURIComponent(kind)+'/'+encodeURIComponent(id));if(current!==generation)return;snapshot=data;$('proposal').textContent=JSON.stringify(data.proposal,null,2);$('evidence').replaceChildren();for(const item of data.evidence){const pre=document.createElement('pre');pre.textContent=item.id+'\n'+(item.content??'[Missing or retracted]')+'\nSHA-256: '+(item.sha256??'none');$('evidence').append(pre);}$('digest').textContent='Snapshot SHA-256: '+data.snapshot_sha256;$('action').value='approve';$('action').options[1].disabled=kind!=='procedure';$('details').hidden=false;status('Review exact proposal and cited text.');}catch(e){status(e.message);}}
$('connect').onclick=async()=>{if(!window.isSecureContext){status('Refused: use HTTPS or loopback.');return;}token=$('token').value;$('token').value='';try{await api('claim?limit=1');$('login').hidden=true;$('workspace').hidden=false;await queue();}catch(e){disconnect();status(e.message);}};
$('inspect').onclick=()=>open($('kind').value,$('target').value.trim());
$('disconnect').onclick=disconnect;$('refresh').onclick=queue;$('kind').onchange=queue;
$('stage').onclick=()=>{if(!snapshot||!$('checked').checked||!$('reason').value.trim()){status('Review evidence, check the box and give a reason.');return;}staged={snapshot_sha256:snapshot.snapshot_sha256,decision:$('action').value,reason:$('reason').value.trim()};$('final').textContent=JSON.stringify({kind:snapshot.kind,id:snapshot.proposal.id,...staged},null,2);$('confirmation').hidden=false;};
$('cancel').onclick=()=>{staged=null;$('confirmation').hidden=true;};
$('submit').onclick=async()=>{if(!snapshot||!staged)return;const item=snapshot,body=staged;staged=null;$('submit').disabled=true;try{await api(item.kind+'/'+encodeURIComponent(item.proposal.id),body);reset();status('Decision recorded. No procedure executed.');}catch(e){reset();status(e.message);}finally{$('submit').disabled=false;}};
for(const id of ['reason','action','checked'])$(id).onchange=()=>{staged=null;$('confirmation').hidden=true;};
window.addEventListener('pagehide',disconnect);
</script></html>'''
